#!/bin/sh

INKSCAPE='/Applications/Inkscape.app/Contents/Resources/bin/inkscape'
SOURCE='../svg'
TEMPFILE='../../temp.svg'
RES='../../app/src/main/res/drawable-'
SIZES='mdpi:2 hdpi:3 xhdpi:4 xxhdpi:6 xxxhdpi:8'

while read p
do
  q=($p)
  version=${q[0]}
  dst=${q[1]}
  width=${q[2]}
  height=${q[3]}
  color=${q[4]}
  src=${q[5]}

  if [ "${version}" == '-' ]
  then
    version=''
  else
    version="-${version}"
  fi
  
  for s in ${SIZES}
  do
    t=(${s//:/ })
    density=${t[0]}
    scale=${t[1]}
    if [ "${color}" == '-' ]
    then
      cp ${SOURCE}/${src}.svg ${TEMPFILE}
    else
      sed -e "s/<path /<path fill=\"${color}\" /g" -e "s/<circle /<circle fill=\"${color}\" /g" ${SOURCE}/${src}.svg > ${TEMPFILE}
    fi
    ${INKSCAPE} -f ${TEMPFILE} -w $((${scale}*${width}/2)) -h $((${scale}*${height}/2)) -e ${RES}${density}${version}/${dst}.png
  done
done < icons.txt
